runtime: php 
env: flex 

runtime_config:
  document_root: public 

skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:O9z31FOrVwG4O6ZcxZl3S13J0ye4IIYB1D/Dwv1aby4=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_POST: 3306
  DB_DATABASE: eventarrangement
  DB_USERNAME: root
  DB_PASSWORD: 123456
  DB_SOCKET: "/cloudsql/miniproject-271309:us-central1:eventarrangement"

beta_settings:
  cloud_sql_instances: "miniproject-271309:us-central1:eventarrangement"